# Generated by Django 4.2.7 on 2025-11-13 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_foreign_key', models.BooleanField(default=False)),
                ('is_nullable', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('scale', models.IntegerField(blank=True, null=True)),
                ('ordinal_position', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordinal_position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('api', 'REST API'), ('file', 'File System'), ('s3', 'AWS S3'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery')], max_length=50)),
                ('connection_string', models.CharField(blank=True, max_length=500)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('definition', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_terms', models.ManyToManyField(blank=True, to='metadata.glossary')),
            ],
            options={
                'verbose_name_plural': 'Glossaries',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='metadata.datasource')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'data_source')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('table_type', models.CharField(choices=[('table', 'Table'), ('view', 'View'), ('materialized_view', 'Materialized View')], default='table', max_length=50)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tables', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='metadata.schema')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'schema')},
            },
        ),
        migrations.CreateModel(
            name='TableGlossaryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.column')),
                ('glossary_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.glossary')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.table')),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('not_null', 'Not Null'), ('unique', 'Unique Values'), ('range', 'Value Range'), ('pattern', 'Regex Pattern'), ('custom_sql', 'Custom SQL')], max_length=50)),
                ('rule_definition', models.TextField(help_text='Rule logic or SQL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='metadata.column')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='metadata.table')),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField()),
                ('failed_count', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='metadata.dataqualityrule')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='metadata.table'),
        ),
        migrations.CreateModel(
            name='DataLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineage_type', models.CharField(choices=[('etl', 'ETL Process'), ('view', 'View Definition'), ('manual', 'Manual Mapping'), ('foreign_key', 'Foreign Key')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('transformation_logic', models.TextField(blank=True, help_text='SQL or transformation logic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_lineage', to='metadata.table')),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_lineage', to='metadata.table')),
            ],
            options={
                'unique_together': {('source_table', 'target_table', 'lineage_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('name', 'table')},
        ),
    ]
