# Generated by Django 4.2.7 on 2025-11-13 13:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={},
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='connection_string',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='database_name',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='host',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='password',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='port',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='username',
        ),
        migrations.AddField(
            model_name='datasource',
            name='processed_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datasource',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='datasource',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datasource',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='data_source_files/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
